version: "3"
services:
  web:
    image: subway:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod,db
    expose:
      - "8080"
    restart: on-failure
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: on-failure
